version: '3.3'
services:
  bot_gB:
    build:
      context: ./
    depends_on:
      - db_gB
    restart: always
    environment:
      BotToken: ${DISCORD_BOT_TOKEN}
      DBHost: db_gB
      DBName: gurglebot
      DB_user: gurglebot
      DBPassw: ${DB_PASSWORD}
  db_gB:
    image: mariadb:latest
    restart: always
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT}
      MYSQL_DATABASE: gurglebot
      MYSQL_USER: gurglebot
      MYSQL_PASSWORD: ${DB_PASSWORD}

volumes:
  db_data: