name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: stardrive

    env:
      DB_IP: ${{ secrets.DB_IP }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_PASSWORD_ROOT: ${{ secrets.DB_PASSWORD_ROOT }}
      DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: Update 3rd party docker containers
        run: docker compose pull

      - name: Build app
        run: docker compose build

      - name: Spin up containers
        run: docker compose up -d